# -*- coding: utf-8 -*-
"""EDA - Gorjetas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYu1w0D0XlG3-__MbtziZNbMbp-B_4P1

# Importando Dados e Traduzindo Dados

## Importando Base de Dados
"""

import pandas as pd

dados = pd.read_csv('tips.csv')
dados.head()

"""## Traduzindo Colunas e Campos"""

dados.columns

renomear = {
    'total_bill': 'valor_da_conta', 
    'tip': 'gorjeta',
    'dessert': 'sobremesa',
    'day': 'dia_da_semana',
    'time': 'refeicao',
    'size': 'total_de_pessoas'
}

type(dados)

gorjetas = dados.rename(columns=renomear)
gorjetas.head()

gorjetas.sobremesa.unique()

sim_nao = {
    'No' : 'Não',
    'Yes': 'Sim'
}

gorjetas.sobremesa.map(sim_nao)

gorjetas.head(1)

gorjetas.sobremesa = gorjetas.sobremesa.map(sim_nao)

gorjetas.head(1)

gorjetas.dia_da_semana.unique()

dias = {
        'Sun': 'Domingo',
        'Sat': 'Sabado',
        'Thur': 'Quinta',
        'Fri': 'Sexta'
}

gorjetas.dia_da_semana = gorjetas.dia_da_semana.map(dias)

gorjetas.head(1)

gorjetas.dia_da_semana.unique()

gorjetas.refeicao.unique()

refeicao = {
    'Dinner': 'Jantar',
    'Lunch': 'Almoço'
}

gorjetas.refeicao = gorjetas.refeicao.map(refeicao)

gorjetas.head(5)

