# -*- coding: utf-8 -*-
"""Data Science - Introdução a Testes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCz0BD12WSUAr3MQT6KYZHP_HDCAaApq

# <font color=green>Aula 1 – Conhecendo os Dados e Explorando

## <font color = blue>Limpando os dados e visualizando uma distribuição
"""

import pandas as pd

tmdb = pd.read_csv('tmdb_5000_movies.csv')
tmdb.head()

tmdb.describe()

import seaborn as sns

ax = sns.distplot(tmdb.vote_average)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no TMDB 5000')

ax = sns.distplot(tmdb.vote_average, norm_hist=False, kde=False)
ax.set(xlabel='Nota Média', ylabel='Frequência')
ax.set_title('Média de votos em filmes no TMDB 5000')

ax = sns.boxplot(x=tmdb.vote_average)
ax.figure.set_size_inches(14,6)
ax.set_xlabel('Nota média do filme', fontsize=16)
ax.set_title('Distribuição de nota média dos filmes do TMDB 5000', fontsize=18)

"""### <font color = pink> Tem algo estranho... Não faz sentido filmes com nota média 0 ou 10..."""

tmdb.query("vote_average == 0").head()

tmdb.query("vote_average == 0").shape[0]

"""### <font color=pink>Analisamos que alguns filmes tiveram poucos ou nenhum voto. Decidimos que esses filmes não devem pertencer a nossa análise"""

tmdb_com_mais_de_10_votos = tmdb.query('vote_count >= 10')
tmdb_com_mais_de_10_votos.describe()

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average, norm_hist=False, kde=False)
ax.set(xlabel='Nota Média', ylabel='Frequência')
ax.set_title('Média de votos em filmes no TMDB 5000 dentre os filmes com 10 ou mais votos')

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no TMDB 5000 dentre os filmes com 10 ou mais votos')

"""#### <font color=pink>Gráfico cumulativo da média das notas por porcentagem cumulativa de filme
Esse gráfico foi aprendido lá na parte de 'visualizando a CDF', mas trouxe para cá para ver o resultado nesses dados também.
"""

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average,
                  kde_kws={'cumulative': True},
                  hist_kws={'cumulative': True})
ax.set(xlabel='Nota Média', ylabel='% acumulada de filmes')
ax.set_title('Média de votos em filmes no TMDB 5000 com 10 ou mais votos')

"""## <font color = blue>Visualizando e limpando o movielens"""

notas = pd.read_csv('ratings.csv')
notas.head()

nota_media_por_filme = notas.groupby('movieId').mean()['rating']
nota_media_por_filme.head()

ax = sns.distplot(nota_media_por_filme.values)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no Movielens 100K')

quantidade_de_votos_por_filme = notas.groupby("movieId").count()
filmes_com_pelo_menos_10_votos = quantidade_de_votos_por_filme.query('rating >= 10').index
filmes_com_pelo_menos_10_votos.values

nota_media_dos_filmes_com_pelo_menos_10_votos = nota_media_por_filme.loc[filmes_com_pelo_menos_10_votos.values]
nota_media_dos_filmes_com_pelo_menos_10_votos.head()

ax = sns.distplot(nota_media_dos_filmes_com_pelo_menos_10_votos.values)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no Movielens 100K com 10 ou mais votos')

ax = sns.boxplot(x=nota_media_dos_filmes_com_pelo_menos_10_votos.values)
ax.set_xlabel('Nota média do filme')
ax.set_title('Distribuição de nota média dos filmes do Movielens 100k dentre os filmes com 10 ou mais votos')

"""## <font color=blue>Visualizando a CDF"""

ax = sns.distplot(nota_media_dos_filmes_com_pelo_menos_10_votos.values,
                  kde_kws={'cumulative': True},
                  hist_kws={'cumulative': True})
ax.set(xlabel='Nota Média', ylabel='% acumulada de filmes')
ax.set_title('Média de votos em filmes no Movielens 100K com 10 ou mais votos')