# -*- coding: utf-8 -*-
"""EDA - Gorjetas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYu1w0D0XlG3-__MbtziZNbMbp-B_4P1

# Importando Dados e Traduzindo Dados

## Importando Base de Dados
"""

import pandas as pd

dados = pd.read_csv('tips.csv')
dados.head()

"""---

## Traduzindo Colunas e Campos
"""

dados.columns

renomear = {
    'total_bill': 'valor_da_conta', 
    'tip': 'gorjeta',
    'dessert': 'sobremesa',
    'day': 'dia_da_semana',
    'time': 'refeicao',
    'size': 'total_de_pessoas'
}

type(dados)

gorjetas = dados.rename(columns=renomear)
gorjetas.head()

gorjetas.sobremesa.unique()

sim_nao = {
    'No' : 'Não',
    'Yes': 'Sim'
}

gorjetas.sobremesa.map(sim_nao)

gorjetas.head(1)

gorjetas.sobremesa = gorjetas.sobremesa.map(sim_nao)

gorjetas.head(1)

gorjetas.dia_da_semana.unique()

dias = {
        'Sun': 'Domingo',
        'Sat': 'Sabado',
        'Thur': 'Quinta',
        'Fri': 'Sexta'
}

gorjetas.dia_da_semana = gorjetas.dia_da_semana.map(dias)

gorjetas.head(1)

gorjetas.dia_da_semana.unique()

gorjetas.refeicao.unique()

refeicao = {
    'Dinner': 'Jantar',
    'Lunch': 'Almoço'
}

gorjetas.refeicao = gorjetas.refeicao.map(refeicao)

gorjetas.head(5)

"""---

---

# Comparando Distribuições de Maneira Explanatória

## Seaborn e Scatterplot
"""

import seaborn as sns

!pip show seaborn

"""### Análise 1 - Valor da Conta e Gorjeta"""

gorjetas.columns

valor_gorjeta = sns.scatterplot(x = 'valor_da_conta', y = 'gorjeta', data = gorjetas)
valor_gorjeta

"""<font color = green> **Visualmente o valor da gorjeta aumenta conforme aumenta o valor da conta**"""

print(f'A base de dados contém {gorjetas.shape[0]}')
print(f'Registros não nulos:')
gorjetas.count()

"""---

## Coluna Porcentagem
"""

gorjetas.head(1)

gorjetas['porcentagem'] = (gorjetas.gorjeta / gorjetas.valor_da_conta) * 100

gorjetas.head()

gorjetas.porcentagem = gorjetas.porcentagem.round(2)

gorjetas.head()

porcentagem_conta = sns.scatterplot(x = 'valor_da_conta', y = 'porcentagem', data = gorjetas)

"""<font color = green> **Visualmente o valor da conta não é proporcional ao valor da gorjeta**

---

## Relplot e Implot
"""

porcentagem_conta_linha = sns.relplot(x = 'valor_da_conta', y = 'porcentagem', kind = 'line', data = gorjetas)

sns.lmplot(x = 'valor_da_conta', y = 'porcentagem', data = gorjetas)

# primeiro_plot.set_title('Análise do valor da gorjeta em função do valor da conta')
# primeiro_plot.set(xlabel='Valor da conta', ylabel='Valor da gorjeta')
# imagem = primeiro_plot.get_figure()
# imagem.savefig('imagem.png')