# -*- coding: utf-8 -*-
"""Introdução a Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkNPoLRZv-Ik_pPCwxUqAiMuGdARh8QB

# Conhecendo nossos dados
"""

import pandas as pd

notas = pd.read_csv('ratings.csv')

notas.head()

notas.shape

notas.columns = ['usuarioId', 'filmeId', 'nota', 'momento']
notas.head()

notas['nota']

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

"""# Visualizando dados com histograma e boxplot"""

notas.nota.plot(kind='hist')

notas.nota.median()

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

