# -*- coding: utf-8 -*-
"""Introdução a Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkNPoLRZv-Ik_pPCwxUqAiMuGdARh8QB

# Aula 1 - Data Science: Dados e Visualização

## Conhecendo nossos dados
"""

import pandas as pd

notas = pd.read_csv('ratings.csv')

notas.head()

notas.shape

notas.columns = ['usuarioId', 'filmeId', 'nota', 'momento']
notas.head()

notas['nota']

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

"""## Visualizando dados com histograma e boxplot"""

notas.nota.plot(kind='hist')

notas.nota.median()

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

"""# Aula 2 - Análise Exploratória

## Análise exploratória de dados e mais gráficos
"""

filmes = pd.read_csv('movies.csv')
filmes. columns = ['filmeId', 'titulo', 'generos']
filmes.head()

notas.head()

notas.query('filmeId == 2').nota.mean()

notas.groupby('filmeId')

notas.groupby('filmeId').mean()

notas.groupby('filmeId').nota.mean()

notas.groupby('filmeId').nota.mean().to_frame()

medias_por_filme = notas.groupby('filmeId').nota.mean()

medias_por_filme.head()

medias_por_filme.plot(kind='hist')

sns.boxplot(medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme)

sns.distplot(medias_por_filme, bins=10)

import matplotlib.pyplot as plt

plt.hist(medias_por_filme)

plt.figure(figsize=(5,8))
sns.boxplot(y=medias_por_filme)

