# -*- coding: utf-8 -*-
"""Data Science - Introdução a Testes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCz0BD12WSUAr3MQT6KYZHP_HDCAaApq

# <font color=green>Aula 1 – Conhecendo os Dados e Explorando

## <font color = blue>Limpando os dados e visualizando uma distribuição
"""

import pandas as pd

tmdb = pd.read_csv('tmdb_5000_movies.csv')
tmdb.head()

tmdb.describe()

import seaborn as sns

ax = sns.distplot(tmdb.vote_average)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no TMDB 5000')

ax = sns.distplot(tmdb.vote_average, norm_hist=False, kde=False)
ax.set(xlabel='Nota Média', ylabel='Frequência')
ax.set_title('Média de votos em filmes no TMDB 5000')

ax = sns.boxplot(x=tmdb.vote_average)
ax.figure.set_size_inches(14,6)
ax.set_xlabel('Nota média do filme', fontsize=16)
ax.set_title('Distribuição de nota média dos filmes do TMDB 5000', fontsize=18)

"""### <font color = pink> Tem algo estranho... Não faz sentido filmes com nota média 0 ou 10..."""

tmdb.query("vote_average == 0").head()

tmdb.query("vote_average == 0").shape[0]

"""### <font color=pink>Analisamos que alguns filmes tiveram poucos ou nenhum voto. Decidimos que esses filmes não devem pertencer a nossa análise"""

tmdb_com_mais_de_10_votos = tmdb.query('vote_count >= 10')
tmdb_com_mais_de_10_votos.describe()

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average, norm_hist=False, kde=False)
ax.set(xlabel='Nota Média', ylabel='Frequência')
ax.set_title('Média de votos em filmes no TMDB 5000 dentre os filmes com 10 ou mais votos')

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no TMDB 5000 dentre os filmes com 10 ou mais votos')

"""#### <font color=pink>Gráfico cumulativo da média das notas por porcentagem cumulativa de filme
Esse gráfico foi aprendido lá na parte de 'visualizando a CDF', mas trouxe para cá para ver o resultado nesses dados também.
"""

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_average,
                  kde_kws={'cumulative': True},
                  hist_kws={'cumulative': True})
ax.set(xlabel='Nota Média', ylabel='% acumulada de filmes')
ax.set_title('Média de votos em filmes no TMDB 5000 com 10 ou mais votos')

"""## <font color = blue>Visualizando e limpando o movielens"""

notas = pd.read_csv('ratings.csv')
notas.head()

nota_media_por_filme = notas.groupby('movieId').mean()['rating']
nota_media_por_filme.head()

ax = sns.distplot(nota_media_por_filme.values)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no Movielens 100K')

quantidade_de_votos_por_filme = notas.groupby("movieId").count()
filmes_com_pelo_menos_10_votos = quantidade_de_votos_por_filme.query('rating >= 10').index
filmes_com_pelo_menos_10_votos.values

nota_media_dos_filmes_com_pelo_menos_10_votos = nota_media_por_filme.loc[filmes_com_pelo_menos_10_votos.values]
nota_media_dos_filmes_com_pelo_menos_10_votos.head()

ax = sns.distplot(nota_media_dos_filmes_com_pelo_menos_10_votos.values)
ax.set(xlabel='Nota Média', ylabel='Densidade')
ax.set_title('Média de votos em filmes no Movielens 100K com 10 ou mais votos')

ax = sns.boxplot(x=nota_media_dos_filmes_com_pelo_menos_10_votos.values)
ax.set_xlabel('Nota média do filme')
ax.set_title('Distribuição de nota média dos filmes do Movielens 100k dentre os filmes com 10 ou mais votos')

"""## <font color=blue>Visualizando a CDF"""

ax = sns.distplot(nota_media_dos_filmes_com_pelo_menos_10_votos.values,
                  kde_kws={'cumulative': True},
                  hist_kws={'cumulative': True})
ax.set(xlabel='Nota Média', ylabel='% acumulada de filmes')
ax.set_title('Média de votos em filmes no Movielens 100K com 10 ou mais votos')

"""# <font color=green>Aula 2 – Explorando as Distribuições das Amostras

## <font color=blue>Visualizando outras informações e quantis quaisquer de forma numérica
"""

ax = sns.distplot(tmdb_com_mais_de_10_votos.vote_count)
ax.set(xlabel='Número de votos', ylabel='Densidade')
ax.set_title('Número de votos em filmes no TMDB 5000 com 10 ou mais votos')

ax = sns.distplot(tmdb.query('budget > 0').budget)
ax.set(xlabel='Budget (gastos)', ylabel='Densidade')
ax.set_title('Gatos em filmes no TMDB 5000')

ax = sns.distplot(tmdb.popularity)
ax.set(xlabel='Popularidade', ylabel='Densidade')
ax.set_title('Popularidade em filmes no TMDB 5000')

ax = sns.distplot(tmdb.runtime)
ax.set(xlabel='Tempo de Duração', ylabel='Densidade')
ax.set_title('Tempo de Duração em filmes no TMDB 5000')

tmdb.runtime.isnull().sum()

ax = sns.distplot(tmdb.query('runtime>0').runtime.dropna())
ax.set(xlabel='Popularidade', ylabel='Densidade')
ax.set_title('Popularidade em filmes no TMDB 5000')

ax = sns.distplot(tmdb.query('runtime>0').runtime.dropna(),
                  hist_kws={'cumulative':True},
                  kde_kws={'cumulative':True})
ax.set(xlabel='Popularidade', ylabel='% de filmes')
ax.set_title('Popularidade em filmes no TMDB 5000')

tmdb.query('runtime>0').runtime.dropna().quantile(.8)

"""# <font color = green>Aula 3 – Testes de Uma Amostra

## <font color=blue>O efeito do tamanho de uma amostra
"""

print(f'Média dos filmes com pelo menos 10 votos: {nota_media_dos_filmes_com_pelo_menos_10_votos.mean()}')

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(75243)
temp = nota_media_dos_filmes_com_pelo_menos_10_votos.sample(frac=1)

medias = [temp[0:i].mean() for i in range(1, len(temp))]

plt.plot(medias)

len(nota_media_dos_filmes_com_pelo_menos_10_votos)

"""## <font color=blue>Intervalo de confiança da média com t e ztest"""

from statsmodels.stats.weightstats import zconfint

zconfint(nota_media_dos_filmes_com_pelo_menos_10_votos)

from statsmodels.stats.weightstats import DescrStatsW

descr_todos_com_10_votos = DescrStatsW(nota_media_dos_filmes_com_pelo_menos_10_votos)
descr_todos_com_10_votos.tconfint_mean()

