# -*- coding: utf-8 -*-
"""Time Series

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QnX5Ckoez0yuH3p0IiZX0BpgXmKRMgfF

# <font color = green>Aula 1 - Tendência das Vendas

## <font color = blackpink>Análise Das Vendas
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
# %matplotlib inline
import matplotlib.pyplot as plt

pd.read_csv('alucar.csv').head()

alucar = pd.read_csv('alucar.csv')

print(f'quantidade de linhas e colunas: {alucar.shape}')

print(f'Quantidade de dados nulos: {alucar.isna().sum().sum()}')

alucar.dtypes

alucar.mes = pd.to_datetime(alucar.mes)

alucar.dtypes

sns.__version__

sns.lineplot(x = 'mes', y = 'vendas', data = alucar)

"""---

## <font color = blackpink>Aperfeiçoando o gráfico
"""

sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x = 'mes', y = 'vendas', data = alucar)
ax.figure.set_size_inches(12, 6)
ax.set_title('Vendas Alucar de 2017 e 2018', loc = 'left', fontsize = 18)
ax.set_xlabel('Meses', fontsize = 14)
ax.set_ylabel('Vendas (R$)', fontsize = 14)
ax = ax

